"""Smoke tests for the `slmkiii surface ...` CLI subcommands.

These tests exercise the CLI handler functions directly with argparse
namespaces so we don't have to spawn subprocesses. The push/run subcommands
that touch real hardware are not exercised here — they're covered by manual
integration testing.
"""

import argparse
import io
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

from slmkiii.cli import cmd_surface_compile, cmd_surface_inspect


def _write_spec(dir_: Path, name: str, plugin: str = 'animoog_z') -> Path:
    spec = dir_ / f'{name}.yaml'
    spec.write_text(
        f'name: {name}\n'
        f'controller: slmkiii\n'
        f'plugin: {plugin}\n'
        f'target: aum\n'
        f'midi_channel_base: 1\n'
        f'parameters:\n'
        f'  - "*"\n'
    )
    return spec


class TestSurfaceCompile(unittest.TestCase):

    def test_compile_produces_per_spec_mozaic(self):
        with tempfile.TemporaryDirectory() as td:
            tdir = Path(td)
            spec = _write_spec(tdir, 'cli_compile_test')
            out = tdir / 'build'
            args = argparse.Namespace(
                spec=str(spec), out_dir=str(out), diagnostic=False)
            buf = io.StringIO()
            with redirect_stdout(buf):
                cmd_surface_compile(args)

            syx_files = list(out.glob('*.syx'))
            map_files = list(out.glob('*.aum_midimap'))
            spec_mozaic = out / 'cli_compile_test.mozaic'
            generic_bridge = out / 'SLMK-BRIDGE.mozaic'

            self.assertGreater(len(syx_files), 0, 'no .syx generated')
            self.assertGreater(len(map_files), 0, 'no .aum_midimap generated')
            self.assertTrue(spec_mozaic.exists(),
                            'per-spec .mozaic should be generated by default')
            self.assertFalse(generic_bridge.exists(),
                             'generic SLMK-BRIDGE only with --diagnostic')

            for f in syx_files + map_files + [spec_mozaic]:
                self.assertGreater(f.stat().st_size, 0, f'{f.name} is empty')

    def test_compile_diagnostic_also_emits_generic_bridge(self):
        with tempfile.TemporaryDirectory() as td:
            tdir = Path(td)
            spec = _write_spec(tdir, 'cli_compile_diag_test')
            out = tdir / 'build'
            args = argparse.Namespace(
                spec=str(spec), out_dir=str(out), diagnostic=True)
            buf = io.StringIO()
            with redirect_stdout(buf):
                cmd_surface_compile(args)

            self.assertTrue((out / 'cli_compile_diag_test.mozaic').exists())
            self.assertTrue((out / 'SLMK-BRIDGE.mozaic').exists())


class TestSurfaceInspect(unittest.TestCase):

    def test_inspect_prints_summary(self):
        with tempfile.TemporaryDirectory() as td:
            spec = _write_spec(Path(td), 'cli_inspect_test')
            args = argparse.Namespace(spec=str(spec))
            buf = io.StringIO()
            with redirect_stdout(buf):
                cmd_surface_inspect(args)
            output = buf.getvalue()
            self.assertIn('cli_inspect_test', output)
            self.assertIn('controller:  slmkiii', output)
            self.assertIn('plugin:      animoog_z', output)
            self.assertIn('Page', output)


if __name__ == '__main__':
    unittest.main()
