"""Generate a spec-specific Mozaic .moz script from a ResolvedMapping.

The output script is the live runtime in the Mac-free architecture: it is
loaded as a Mozaic AUv3 inside AUM, sits between SL MkIII USB MIDI and the
plugin chain, forwards CCs to the plugin, and emits InControl SysEx back to
SL MkIII to keep its top-row screens in sync with the values flowing through.

No dynamic protocol is needed — every label, color, CC slot, and screen
update is baked in at compile time. This means the script is fixed for a
given spec; change the spec, recompile, re-push, re-tap.
"""

from __future__ import annotations

import io
from textwrap import dedent

from controlmap.model import MsgType, ResolvedMapping
from controlmap.mozaic import incontrol_codec as ic


# 8 knob columns are the live "screen" surface on the SL MkIII.
KNOB_SCREEN_COLUMNS = 8


def _color_for_param(name: str) -> int:
    """Pick a palette colour for a parameter based on its name. Cheap heuristic
    so the generated script doesn't need a metadata-driven theme."""
    n = name.lower()
    if any(k in n for k in ('cutoff', 'filter', 'reso')):
        return ic.COLOR_CYAN
    if any(k in n for k in ('gain', 'level', 'volume', 'amp')):
        return ic.COLOR_GREEN
    if 'pan' in n:
        return ic.COLOR_YELLOW
    if any(k in n for k in ('delay', 'reverb', 'verb', 'wet', 'fx')):
        return ic.COLOR_PURPLE
    if any(k in n for k in ('attack', 'decay', 'release', 'sustain', 'env')):
        return ic.COLOR_ORANGE
    return ic.COLOR_WHITE


def _emit_sysex_send(name: str, data: tuple[int, ...]) -> str:
    """Inline a SysEx as a series of buf assignments + SendSysex."""
    parts = []
    for i, b in enumerate(data):
        parts.append(f'    buf[{i}] = {b}')
    parts.append(f'    SendSysex buf, {len(data)}')
    return '\n'.join(parts)


def generate(resolved: ResolvedMapping, page_index: int = 0) -> str:
    """Build the .moz script source for a single page of a ResolvedMapping.

    Phase 1 covers the top-row knob screens (8 columns). Buttons, pads,
    multi-page, and LED feedback are deferred to a later iteration."""
    if not resolved.page_set.pages:
        raise ValueError('cannot generate Mozaic script: no pages in mapping')

    page = resolved.page_set.pages[page_index]
    spec_name = resolved.spec.name
    plugin_name = resolved.metadata.get('plugin', spec_name)

    # Collect knob bindings in column order. Only knob slots 0..7 drive the
    # SL MkIII top-row screens; deeper knob indexes have no screen.
    knob_bindings: dict[int, object] = {}
    for b in page.bindings:
        slot = b.slot
        if (slot.group == 'knobs' and slot.index < KNOB_SCREEN_COLUMNS
                and b.msg_type is MsgType.CC):
            knob_bindings[slot.index] = b

    out = io.StringIO()
    out.write(dedent(f"""\
        // Auto-generated by controlmap.mozaic.generator — DO NOT EDIT.
        // Spec: {spec_name}  Plugin: {plugin_name}  Page: {page.name}
        //
        // Loaded as a Mozaic AUv3 inside AUM. Sits between the SL MkIII USB
        // MIDI input and the plugin chain. Forwards CCs to the plugin and
        // emits InControl SysEx back to the SL MkIII so its top-row screens
        // track values originating anywhere in the routing.

        @OnLoad
            SetShortName {{{spec_name[:7].upper()}}}
            ShowLayout 0
            LabelPads {{Auto-generated bridge for {plugin_name}}}
            Log {{loaded: {spec_name}}}

            // cc_to_col[ch*128 + cc] = column 0..7 for binding, or -1 if none.
            FillArray cc_to_col, -1, 2048
        """))

    # Build the (channel, cc) -> column lookup setup.
    for col, binding in sorted(knob_bindings.items()):
        ch = binding.midi_channel - 1  # type: ignore[attr-defined]
        cc = binding.midi_cc            # type: ignore[attr-defined]
        out.write(f'    cc_to_col[{ch * 128 + cc}] = {col}\n')

    out.write(dedent("""\

            Call @SetupScreens
        @End

        @SetupScreens
            // Set every column to KNOB layout, with parameter label + colour.
        """))

    # Set knob layout once across all 8 columns.
    layout_msg = ic.set_layout(ic.LAYOUT_KNOB)
    out.write(_emit_sysex_send('buf', layout_msg) + '\n\n')

    # For each column, write label, color, and an initial value of 0.
    for col in range(KNOB_SCREEN_COLUMNS):
        binding = knob_bindings.get(col)
        if binding is not None:
            label = (binding.param.display_name  # type: ignore[attr-defined]
                     or binding.param.param_path.split('.')[-1])  # type: ignore[attr-defined]
            color = _color_for_param(label)
        else:
            label = ''
            color = ic.COLOR_OFF
        out.write(f'    // column {col}: {label!r}\n')
        out.write(_emit_sysex_send('buf', ic.set_text(col, 0, label)) + '\n')
        out.write(_emit_sysex_send('buf', ic.set_color(col, 0, color)) + '\n')
        out.write(_emit_sysex_send('buf', ic.set_value(col, 0, 0)) + '\n\n')

    # Runtime path: forward CC + emit set_value sysex if column is bound.
    # set_value frame: F0 00 20 29 02 0A 01 02 col 03 0 val F7  (13 bytes)
    val_template, val_pos = ic.set_value_template(0, 0)  # placeholder col=0
    # Index of the column byte in the template (PROP_VALUE setup):
    # header(7) + CMD(1) -> column at index 8.
    col_pos = len(ic.INCONTROL_HEADER) + 1
    out.write(dedent(f"""\
        @End

        @OnMidiCC
            // Pass through to plugin chain unchanged.
            SendMIDICC MIDIChannel, MIDIByte2, MIDIByte3

            idx = MIDIChannel * 128 + MIDIByte2
            col = cc_to_col[idx]
            if col >= 0
                Call @EmitSetValue
            endif
        @End

        @EmitSetValue
        """))
    # Emit the static template, then patch column + value bytes per call.
    for i, b in enumerate(val_template):
        out.write(f'    val_buf[{i}] = {b}\n')
    out.write(f'    val_buf[{col_pos}] = col\n')
    out.write(f'    val_buf[{val_pos}] = MIDIByte3\n')
    out.write(f'    SendSysex val_buf, {len(val_template)}\n')
    out.write('@End\n')

    return out.getvalue()
